spring:
  datasource:
    username: root
    password: QRwudi666!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/znyg?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://rm-uf689n11q0q059b678o.mysql.rds.aliyuncs.com:3306/znyg?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  application:
    name: znyg
  quartz:
    # 将任务等保存化到内存
    job-store-type: memory
    # 自动启动
    auto-startup: true
    # 程序结束时会等待quartz相关的内容结束
    wait-for-jobs-to-complete-on-shutdown: true
    # QuartzScheduler启动时更新己存在的Job,这样就不用每次修改targetObject后删除qrtz_job_details表对应记录
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          # 线程池相关
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            # 线程数
            threadCount: 5
            # 线程优先级
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  mail:
    host: smtp.163.com
    username: qr
    password: DTYMUYXGCOKSIYEU

server:
  port: 10000
  servlet:
    context-path: /znyg

mybatis-plus:
  mapper-locations: classpath*:zhku/graduation/core/modules/**/xml/*Mapper.xml
  global-config:
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: auto
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 执行的sql 输出到控制台
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true

# swagger 自定义配置
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 智能鱼缸管理和监控软件
  try-host: http://localhost:${server.port}
  protocols:
    - http
    - https