spring:
  security:
    user:
      password: 123456
      name: user
  datasource:
    username: root
    password: QRWUDI666
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/znyg?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
server:
  port: 80
  servlet:
    context-path: /znyg

mybatis-plus:
  global-config:
    banner: false